spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campfire
    username: postgres
    password: password # Ensure this is your actual local PostgreSQL password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
