#!/usr/bin/env bash

if [[ "$1" == "-c" || "$1" == "--clean" ]]; then
    echo "Cleaning..."
    rm exe_timetable
elif [[ "$1" == "-h" || "$1" == "--help" ]]; then
    echo "Usage: ./run [options]"
    echo "Options:"
    echo "  -o, --only            Only compiles, no execute"
    echo "  -c, --clean           Clean up everything"
    echo "  -h, --help            Print this message"
    echo "  [no args]             Compile and execute"
elif [[ "$1" == "-o" || "$1" == "--only" ]]; then
    echo "Only recompiling..."
    if gcc -o exe_timetable generate.c person.c -Wall -Wextra -g -O3; then
        echo "execute with ./exe_timetable"
    fi
else
    if [[ ! -f exe_timetable || generate.c -nt exe_timetable || person.c -nt exe_timetable ]]; then
        echo "Compiling..."
        gcc -o exe_timetable generate.c person.c -Wall -Wextra -g -O3
    else
        echo "Skipping compilation"
    fi

    echo "Executing..."
    ./exe_timetable
fi

